version: '3.8'

services:
  api-gateway:
    build: .
    image: ai-pc-advisor/api-gateway
    container_name: api-gateway
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - ai-pc-advisor-network
    volumes:
      - ./logs:/usr/src/app/logs

  redis:
    image: redis:7-alpine
    container_name: api-gateway-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ai-pc-advisor-network

networks:
  ai-pc-advisor-network:
    name: ai-pc-advisor-network
    driver: bridge

volumes:
  redis-data: 